listening-port=3478
external-ip=69.62.110.2
realm=turn.seemaai.co.uk
server-name=turn.seemaai.co.uk
use-auth-secret
static-auth-secret=5ff29ab65af22d6e33632ba73e7a2da73a8bbd46048be1502118d44af83101bd
min-port=50200
max-port=50300
no-cli
no-tlsv1
no-tlsv1_1
fingerprint
stale-nonce=600
log-file=stdout
